### ISSUE TITLE
Changing from our own css to using bootstrap

### ISSUE THREAD

**Issue by deweesa** [deweesa/Leaguerboard#26]
- [x]  Individual Champion
- [ ]  Champion Roster
- [x]  Team Selection
- [x]  Team
- [x]  Summoner Selection
- [x]  Summoner
- [x]  Home page
- [x]  Base template

https://pythonhosted.org/Flask-Bootstrap/index.html
~~https://getbootstrap.com/docs/5.0/getting-started/introduction/~~ Wrong version for flask-bootstrap extension
https://getbootstrap.com/docs/3.3/components/#navbar

**Comment by deweesa** [comment]
I'll hit the Champ pages and work on base html for navbar and footer.

**Comment by Stumblzzz** [comment]
I'll tackle Summoner

**Comment by deweesa** [comment]
@Stumblzzz Just a heads up, the bootstrap extension for flask uses Bootstrap v3.3.7, where the OG link I posted for bootstrap is for v5.something

**Comment by deweesa** [comment]
Gonna move the champ select to it's own issue for this week since its been a bit tricky
